version: 0.0 # 항상 0.0고정(AWS규칙)
os: linux # EC2가 Ubuntu로 Linux

# S3에서 받은 파일을 EC2어디에 복사할지 정의
files:
  - source: / # S3에서 다운받은 압축 해제된 파일 전체
    destination: /home/ec2-user/app/step2/zip  # 배포될 경로(복사될 경로)
    overwrite: yes # 덮어쓰기

# 복사된 파일들의 소유권을 누구로 설정할지 정의
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
# 왜필요해? CodeDeploy Agent는 root권한으로 파일을 복사함.
# 그럼 복사된 파일 소유자가 root가 되서 ubuntu유저로 실행하는 스크립트가 파일에
# 접근 못할 수 있음. 그래서 ubuntu로 명시적으로 지정하는 것임.

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user